### ISSUE TITLE
CDB: CockroachDB Support Epic

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#10491]
## Problem

With the release of CockroachDB Serverless, we're seeing a lot of requests to support CockroachDB. Since CockroachDB is wire-compatible with Postgres, we mostly do support it, but there's some hiccups. The work below aims to smooth out these hiccups.

## Getting to Preview

- [x] https://github.com/prisma/prisma-engines/pull/2423
- [x] #10079
- [x] https://github.com/prisma/prisma/issues/10514
- [x] #10492
- [x] #10493 
    - Look into what needs to be done to disable the methods.
- [x] https://github.com/prisma/prisma/issues/6552
	- [x] https://github.com/prisma/prisma/issues/10667
	- [x] https://github.com/prisma/prisma/issues/10665
- [x] #10496
- [x] https://github.com/prisma/prisma/issues/9978
- [x] #10494
- [x] https://github.com/prisma/prisma/issues/10852
- [x] https://github.com/prisma/prisma/issues/11015
- [x] https://github.com/prisma/prisma/issues/10808
- [ ] https://github.com/prisma/docs/issues/2539

## Getting to GA

- [x] #4702 

## Additional context

- Community Issue: https://github.com/prisma/prisma/issues/2523

**Comment by floelhoeffel** [comment]
Database connector and introspection are in preview as of `3.9.0` - https://github.com/prisma/prisma/releases/tag/3.9.0

Migrations work is next.

**Comment by floelhoeffel** [comment]
Migrations were added with '3.11.0' https://github.com/prisma/prisma/releases/tag/3.11.0

**Comment by floelhoeffel** [comment]
Douplicate of #12385
