### ISSUE TITLE
`referentialIntegrity` GA

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#11441]
[Internal Notion document
](https://www.notion.so/prismaio/How-do-we-GA-the-referentialIntegrity-preview-feature-8a656fe445ae4a69ad19c5000e5c7191)

## Necessary

Issues we need to close before GA (or move to the optional section below):

- [x] https://github.com/prisma/prisma/issues/9380
- [x] https://github.com/prisma/prisma/issues/15601
- [x] https://github.com/prisma/prisma/issues/15655
- [x] https://github.com/prisma/prisma/issues/10807
	- [x] https://github.com/prisma/prisma/issues/10806 
- [x] https://github.com/prisma/language-tools/issues/991
- [x] https://github.com/prisma/docs/issues/3832
 
##### Client team
- [x] https://github.com/prisma/prisma/issues/13766
- [x] https://github.com/prisma/prisma/issues/12557
- [x] https://github.com/prisma/prisma/issues/10935
- [x] https://github.com/prisma/prisma/issues/10000
- [x] https://github.com/prisma/prisma/issues/10581

##### Schema team
- [x] https://github.com/prisma/prisma/issues/14673
- [x] https://github.com/prisma/prisma/issues/11022
- [x] https://github.com/prisma/prisma/issues/11498
- [ ] https://github.com/prisma/prisma/issues/12582 (probably unrelated to feature)
- [x] https://github.com/prisma/prisma/issues/15225

#### Unconfirmed
- [x] https://github.com/prisma/prisma/issues/14271
- [x] https://github.com/prisma/prisma/issues/12378
- [x] https://github.com/prisma/prisma/issues/12256

#### Unknown
- [x] https://github.com/prisma/prisma/issues/12288

#### Already fixed/closed before we started GA work
- [x] https://github.com/prisma/prisma/issues/11191
- [x] https://github.com/prisma/prisma/issues/11469
- [x] https://github.com/prisma/prisma/issues/10758

### Features to decide

- [ ] https://github.com/prisma/prisma/issues/10611
- [x] https://github.com/prisma/language-tools/issues/992
- [ ] https://github.com/prisma/prisma/issues/10173
- [ ] https://github.com/prisma/language-tools/issues/946

### Internal
- [x] https://github.com/prisma/prisma/issues/7936
- [x] https://github.com/prisma/prisma/issues/6927

## Optional

Issues that could wait until after GA:

- [ ] https://github.com/prisma/prisma/issues/7351
- [ ] https://github.com/prisma/prisma/issues/9571
- [ ] https://github.com/prisma/prisma/issues/1469
- [ ] https://github.com/prisma/prisma/issues/10843
- [ ] https://github.com/prisma/prisma/issues/10102

**Comment by janpio** [comment]
Release with 4.7.0. Documentation at: https://www.prisma.io/docs/concepts/components/prisma-schema/relations/relation-mode
