### ISSUE TITLE
[Epic] `migrate diff` and `db execute` GA

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#12136]
# Feature Work

- [ ] add --exit-code option to migrate diff, #9707, #11566
- [ ] improve summaries for diff and reset #11545

# Bugs

- [ ] Sqlite file path resolution #11626

# Documentation

## Reference

- [x] CLI docs

## Use cases

- [ ] squashing complete migrations history
- [ ] squashing newly created migrations on a branch
- [x] fixing failed migrations forward
- [x] rolling failed migrations back

# Polishing

- [x] align help / usage text output better in diff
- [ ] output on db execute when using wrong param (just usage part of -h)

# Stabilizing

- [ ] Remove --preview-flag from command
- [ ] Remove --preview-flag from help texts
- [ ] Remove --preview-flag from docs
