### ISSUE TITLE
TERR: Type-safe Structured Errors

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#12340]
## Problem

From @Sytten:

> We sometimes want to handle SQL errors differently to return a proper error to the frontend. For example, we might want to display email already used if a unique violation is detected on the field. The current situation is that we have to check against an obscure error code (P2002 for example for unique validation failure) and then go into meta.target to get which field broke. Its never easy to extract meaningful stuff from ORM(-like) tools despite being a very common operation and I think it could be a factor of differentiation for prisma.

## Tasks

- [ ] Finalize design document
- [ ] Finish up Engines PR
   https://github.com/prisma/prisma-engines/pull/2451
- [ ] Integrate and merge
   https://github.com/prisma/prisma/issues/10747
- [ ] Close PR with a nice message about our new error support: 
   https://github.com/prisma/prisma/pull/10996

## Reference

- Community Issue: https://github.com/prisma/prisma/issues/5040
