### ISSUE TITLE
Interactive Transaction GA

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#12363]
This epic is about getting Interactive Transactions out of preview.

## Tasks

- [x] https://github.com/prisma/prisma/issues/11750
- [x] https://github.com/prisma/prisma/issues/11913
- [x] https://github.com/prisma/prisma/issues/12145
- [x] Close #8664
- [x] https://github.com/prisma/prisma/issues/12862
- [x] https://github.com/prisma/prisma/issues/12663

## To reproduce

- [x] https://github.com/prisma/prisma/issues/12516
- [x] https://github.com/prisma/prisma/issues/12277

## Discussion needed

- [x] https://github.com/prisma/prisma/issues/6156

## Nice to have

- [x] https://github.com/prisma/prisma/issues/12277

We should also look to see if any other issues popped up as we were stabilizing this feature.

**Comment by DamianGlowala** [comment]
Two other issues worth looking at for the GA release:
https://github.com/prisma/prisma/issues/11511
https://github.com/prisma/prisma/issues/10880

**Comment by iddan** [comment]
Hey, is there a plan for when interactive transactions are expected to be safe to use in production? The product I'm currently working on can really benefit from it.

**Comment by apalumbo** [comment]
Hi @garrensmith @millsp thank you for your contribution and your work. As i see both are assignees of the issue I would like to ask you if there is an estimation on when this feature will exit the preview.
