### ISSUE TITLE
[Epic] extendedIndexes GA

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#12376]
The feature currently encompasses the `sort` and `length` arguments as well as the `type` argument on Postgres. 
It was released in 3.5 and 3.6 (`type`).
Main docs here: https://www.prisma.io/docs/concepts/components/prisma-schema/indexes
Preview feature feedback can be found here. https://github.com/prisma/prisma/issues/10540

Stabilizing this is a BREAKING CHANGE.

# Feature Work

- [ ] support GiST (might make sense as a separate preview though) https://github.com/prisma/prisma/issues/10634
- [ ] Mysql length limits config dependent that one needs some more investigation https://github.com/prisma/prisma/issues/10990

# Bugs

- [ ]diff and duplicate key error upon second migrate dev run https://github.com/prisma/prisma/issues/10405
- [ ] recreation of indexes https://github.com/prisma/prisma/issues/11631

# Documentation

## Reference

- [ ] Mysql length limits and db configuration
- [ ] Sort order effects in singular vs compound index

## Use cases

- [ ] covering indexes 

# Polishing

- [ ] error message to use length on text in mysql https://github.com/prisma/prisma/issues/10292
- [ ] (maybe) add info to dmmf https://github.com/prisma/prisma/issues/3998

# Stabilizing

- [ ] Remove extendedIndexes preview feature from datamodel
- [ ] Remove extendedIndexes preview feature from docs
- [ ] Upgrade guide since this is a breaking change

## Issues to close after GA
- [ ] https://github.com/prisma/prisma/issues/8661

**Comment by sourdzl** [comment]
really appreciate this work prisma team!   I've been having trouble getting prisma to not create migrations dropping a GIN index i tried adding manually to the db, so this feature would really help!

**Comment by janpio** [comment]
Can you quickyl create a separate issue about what you are seeing @sourdzl? Currently GIN and GiST is _not_ part of `extendedIndexes`, and any additional input could be valuable there. (As you can see above, looking into these two additional types _is_ on our plan here.)

**Comment by sourdzl** [comment]
sure @janpio !

We have a JSONB column in postgres which is shallow (just string key/value pairs, no nesting.). We'd like to index the keys which will be used commonly for WHERE and JOIN filtering, and it seems a GIN index solves this perfectly.

We're happy with any solution that allows the GIN indices to exist - so far we keep having prisma generate migrations that drop the GIN index.  specifying a `type: GIN` would be great, but are also fine with manually adding `CREATE INDEX...` queries to migrations ourself if that's easier to support.

thank you all for maintaining such a great project!

**Comment by pimeys** [comment]
@sourdzl I did some digging what we should be doing here. It's not final proposal, which I'm doing this week so we can write the code. Can you see if it misses something that you'd want to see in the feature?

https://github.com/pimeys/writing/blob/main/prisma/PostgreSQL%20Index%20Types.md

I'm trying to cover Gin, GiST, SP-GiST and BRIN indices, and the default built-in operators. The tsvector stuff foll full-text queries will be coming later this year.

**Comment by pimeys** [comment]
Discovery what is the issue with index lengths on MySQL and what we could do here: https://github.com/pimeys/writing/blob/main/prisma/Discovery:%20MySQL%20Index%20Length%20Limitations.md

**Comment by sourdzl** [comment]
@pimeys thanks for writing such a detailed proposal.  It definitely meets our immediate need (GIN index on JSONB column type, so we can do fast checks of top level key presence).  I suspect the GIN/GIST support will be broadly useful for other postgres users.

Farther down the line, we'd like to try some of the full text searching features as well, but also realize postgres is not the best choice for search overall.  For us, GIN/GIST indexing are "must have" feature.

(sorry for the delayed response)

**Comment by pimeys** [comment]
GIN/GIST/SP-GiST/BRIN work going on here: https://github.com/prisma/prisma-engines/pull/2858

**Comment by janpio** [comment]
And that is merged, you can use `prisma@dev` and the `extendedIndexes` preview feature if you want to play with it. Optimally start with a `db pull` on your existing database that uses these, and see if they are added correctly to the introspected schema.

**Comment by pimeys** [comment]
We are GA.
