### ISSUE TITLE
CRDBGA: CockroachDB General Availability Epic

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#12385]
## Overview

This epic tracks progress towards the CockroachDB General Availability release.

Preview feature feedback issue: https://github.com/prisma/prisma/issues/11542

## Must have

- [ ] https://github.com/prisma/docs/issues/2539
- [ ] https://github.com/prisma/prisma/issues/12383
- [ ] https://github.com/prisma/prisma/issues/12384
- [ ] https://github.com/prisma/prisma/issues/12113
- [ ] https://github.com/prisma/prisma/issues/12239
- [ ] https://github.com/prisma/prisma/issues/11527

### Native types

- [ ] https://github.com/prisma/prisma/issues/12237
- [ ] https://github.com/prisma/prisma/issues/12234
- [ ] https://github.com/prisma/prisma/issues/12236

### Client

- [ ] https://github.com/prisma/prisma/issues/11317

### Bugs

- [ ] https://github.com/prisma/prisma/issues/12281
- [ ] https://github.com/prisma/prisma/issues/12244
- [ ] https://github.com/prisma/prisma/issues/11904

## Nice to have

- [ ] https://github.com/prisma/prisma/issues/12360
- [ ] https://github.com/prisma/prisma/issues/12280
- [ ] https://github.com/prisma/prisma/issues/11866
- [ ] https://github.com/prisma/prisma/issues/11347
- [ ] https://github.com/prisma/prisma/issues/10833

## After GA

- [ ] https://github.com/prisma/prisma/issues/12114

### Client

- [ ] https://github.com/prisma/prisma/issues/11127
- [ ] https://github.com/prisma/prisma/issues/11685

**Comment by tomhoule** [comment]
We released the cockroachdb connector in 3.14, so this is done :tada: 

Follow-up epic for polishing: https://github.com/prisma/prisma/issues/13297
