### ISSUE TITLE
EXC: Extending the Prisma Client Support

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#12394]
## Problem

Unlike many other ORMs the Prisma Client isn't very extendable:
- You can't add custom methods to your models.
- You can't write custom validation.
- You can't exclude certain fields
- You can't group database calls into a logical action (e.g. a signup action may need multiple queries to the database)

To counteract some of these restrictions, we wrote some guides on how to do handle these patterns in your application manually. 

- Custom Validation: https://www.prisma.io/docs/concepts/components/prisma-client/custom-validation
- Computed Fields: https://www.prisma.io/docs/concepts/components/prisma-client/computed-fields
- Excluding Fields: https://www.prisma.io/docs/concepts/components/prisma-client/excluding-fields
- Custom Models: https://www.prisma.io/docs/concepts/components/prisma-client/custom-models

This was a good initial step, but we'd like to start baking some of these patterns into the client itself.

## Tasks

- [ ] EXC: Create a design document discussing the API
- [ ] EXC: Share the design with the community
- [ ] EXC: Finalize design and break down into subsequent tasks

## Reference

- Community Issue: https://github.com/prisma/prisma/issues/7161. There's a ton of good feedback in here.

**Comment by matthewmueller** [comment]
I'd also have a look at the Model and Field sections from the [Feature Matrix](https://www.notion.so/prismaio/Prisma-Client-Feature-Matrix-f559abdd7be54c7ab859db0006f10552) for ideas.
