### ISSUE TITLE
OBS: Observability Foundation Epic

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#12466]

**Comment by garrensmith** [comment]
Internal tech spec https://www.notion.so/prismaio/Metrics-for-Observability-7744be00a8f8481784d06a4c3c4619d9?d=023376dc66ff4ccf9c64016756b26baf

Metrics Tickets:

- [ ] https://github.com/prisma/prisma/issues/12874
- [ ] https://github.com/prisma/prisma/issues/12875
- [ ] https://github.com/prisma/prisma/issues/12876
- [ ] https://github.com/prisma/prisma/issues/12877

**Comment by garrensmith** [comment]
I've moved the Metrics to its own Epic https://github.com/prisma/client-planning/issues/2

**Comment by matthewmueller** [comment]
Maybe we close this epic in favor of the more specific ones?
