### ISSUE TITLE
CRDBNTH: CockroachDB connector polishing epic

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#13297]
# Overview

This is the follow up to https://github.com/prisma/prisma/issues/12385 since the connector has been stabilized.

## Performance

- [ ] https://github.com/prisma/prisma/issues/12384
- [x] https://github.com/prisma/prisma/issues/11317

## Tests
- [ ] https://github.com/prisma/prisma/issues/13268

## Nice to have

- [x] https://github.com/prisma/prisma/issues/11347
- [x] https://github.com/prisma/prisma/issues/12280
- [x] https://github.com/prisma/prisma/issues/10833
- [x] https://github.com/prisma/prisma/issues/12282

## Longer term

- [ ] https://github.com/prisma/prisma/issues/11183
- [x] https://github.com/prisma/prisma/issues/12114
- [x] https://github.com/prisma/prisma/issues/11866
   - [x] https://github.com/prisma/prisma/issues/11904

### Client

- [ ] https://github.com/prisma/prisma/issues/11127
- [ ] https://github.com/prisma/prisma/issues/11685

**Comment by FGoessler** [comment]
Hi,

We’ve noticed there hasn’t been activity on this issue for quite some time, and we suspect it might no longer be relevant. As part of our ongoing effort to streamline open issues in this repository, we’re closing this one to focus on what’s most important to our community.

If you believe this issue is still relevant and requires attention, feel free to reopen it. Reopening the issue is a valuable signal to us about what matters most to you.

You can learn more about our approach and motivations in the [Prisma ORM Manifesto](https://www.prisma.io/blog/prisma-orm-manifesto#1-defining-first-class-databases).

With love,
Your Prisma ORM Team ❤️
