### ISSUE TITLE
Epic: Scalar List Defaults

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#13318]
There is an [accepted PSL proposal](https://www.notion.so/prismaio/Proposal-Scalar-List-Defaults-94d0891a3355475999f10b270e2a311a) about supporting scalar list defaults in `@default(...)` attributes. We want to release this with in the next major version. This issue is about tracking implementation work for that feature.

### 1. Allow scalar list defaults in PSL
- [x] https://github.com/prisma/prisma/issues/13319

### 2. Implement support in engines and language tools. All these tasks depend on (1.).
- [x] https://github.com/prisma/prisma/issues/13320
- [x] https://github.com/prisma/prisma/issues/13321
- [x] https://github.com/prisma/prisma/issues/13322
- [x] https://github.com/prisma/language-tools/issues/1159

## Bug issues

- [x] https://github.com/prisma/prisma/issues/8330
- [x] https://github.com/prisma/prisma/issues/11379

**Comment by tomhoule** [comment]
This is implemented, documented, and shipping in Prisma 4.
