### ISSUE TITLE
referentialIntegrity/relationMode preview feature: Make `NoAction` a synonym/alias of `Restrict` for the emulation, for all databases except PostgreSQL & SQLite.

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#15655]
More details in https://www.notion.so/prismaio/How-do-we-GA-the-referentialIntegrity-preview-feature-8a656fe445ae4a69ad19c5000e5c7191#66d361e2770c4bedb619a2a3052f884c

We decided that for Prisma's emulation we want to make `NoAction` an alias of `Restrict` except for PostgreSQL and SQLite, where we want to make it invalid and have a validation error like `NoAction is not implemented for PostgreSQL and SQLite, you could try using Restrict, which behaves the same if you do not need to defer constraint checks in a transaction, see docs at`

When using `referentialIntegrity = "prisma"`:

Current situation
- NoAction does nothing. Which is "broken".

What we want
- NoAction does the same as Restrict
- NoAction is valid for all databases except PostgreSQL and SQLite
- NoAction is invalid for PostgreSQL and SQLite with a validation error message

After the engines part is done, we want to validate with prisma/prisma tests based on https://github.com/prisma/prisma/pull/14221

## TODOs:

- [x] https://github.com/prisma/prisma-engines/pull/3274
- [x] https://github.com/prisma/prisma-engines/pull/3276
- [x] (Optional for closing this issue, potential useful right after) TypeScript tests that mirror the Rust tests (I think we can still ship this with , as the Rust tests are already kicking in, but longer term these new TS tests could make sense as we want to make sure the Rust side is aligned with the TS side)

**Comment by jkomyno** [comment]
Closed as all related tasks are done.
