### ISSUE TITLE
Epic: The absolute minimum feature set for the views

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#17114]
- Add `view` block to replace the `model` + `// @view` comment annotation hack our users came up with. It works exactly like a model otherwise (including any potential problems that might have with pointing to a view).
    - It is ignored in Migrate and hence does not create a table/view on migration
    - The relations to/from views are totally ignored in migrations
    - Behind preview feature `views`

Internal design document: https://www.notion.so/Views-c1373f139d8b49798187186319c8c84e

## Subtasks

- [x] https://github.com/prisma/prisma/issues/17115
- [x] https://github.com/prisma/prisma/issues/17117
- [x] https://github.com/prisma/language-tools/issues/1346
- [x] https://github.com/prisma/docs/issues/4296

## Bonus tasks

- [x] https://github.com/helix-editor/helix/issues/5385
- [x] https://github.com/pimeys/emacs-prisma-mode/issues/14
- [ ] https://github.com/pantharshit00/vim-prisma/issues/8
- [x] https://github.com/victorhqc/tree-sitter-prisma/issues/40
