### ISSUE TITLE
EPIC: Handle database views in introspection

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#17412]
We should be able to introspect views correctly to the PSL from the database.

## Tasks

- [x] https://github.com/prisma/prisma/issues/17413
- [x] https://github.com/prisma/prisma/issues/17414
- [x] https://github.com/prisma/prisma/issues/17415
- [x] https://github.com/prisma/prisma/issues/17416
- [ ] https://github.com/prisma/prisma/issues/17417
- [x] https://github.com/prisma/prisma/issues/17418

**Comment by janpio** [comment]
Closing, as remaining sub task for MongoDB can be handled on its own.
