### ISSUE TITLE
Prisma Client: make `jsonProtocol` GA 

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#19310]
Context: https://www.prisma.io/blog/prisma-and-serverless-73hbgKnZ6t

- [x] Check [issues](https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3A%22topic%3A+jsonProtocol%22+sort%3Aupdated-desc) with `jsonProtocol` topic tag 
- [x] Bugs
	- [x] Check potential issue https://github.com/prisma/prisma/issues/18095#issuecomment-1551977599
		- [x] https://github.com/prisma/prisma/issues/19373
	- [x] https://github.com/prisma/prisma/issues/19303
		- [x] engines PR https://github.com/prisma/prisma-engines/pull/3966
		- [x] TS PR: https://github.com/prisma/prisma/pull/19474
	- [x] we want to support the shortcut: https://github.com/prisma/prisma/issues/18906
	- [x] https://github.com/prisma/prisma/issues/18846
		- [x] https://github.com/prisma/prisma/pull/19414
	- [x] https://github.com/prisma/prisma/issues/18970
		- [x] PR: https://github.com/prisma/prisma/pull/19154 
	- [x] we want to remove the OR shortcut and make it a breaking change https://github.com/prisma/prisma/issues/18885 
		Context: https://github.com/prisma/prisma-engines/pull/1500
	- [x] Close? https://github.com/prisma/prisma/issues/16184 
- [x] Make `jsonProtocol` the default for Prisma Client 
	- [x] https://github.com/prisma/team-orm/issues/194
- [x] Make `jsonProtocol` the default for Prisma Studio
	- [x] https://github.com/prisma/studio-code/pull/484 
- [ ] Inform and close https://github.com/prisma/prisma/issues/18095
- [x] Deprecate preview feature flag
	- [x] https://github.com/prisma/prisma-engines/pull/4047 
- [ ] Update docs https://github.com/prisma/docs/issues/4854
- [ ] Anything else?
