### ISSUE TITLE
Rename migration-engine to schema-engine

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#19321]
We want to rename `migration-engine`, a Rust binary which is no longer used just for `prisma migrate` commands, but also e.g. for `prisma db pull`. The proposed new name is:
**schema-engine**. [[See Slack thread](https://prisma-company.slack.com/archives/C02FNFLDUS3/p1680182292384679)](https://prisma-company.slack.com/archives/C02FNFLDUS3/p1680182292384679).

## Tasks

- [ ]  prisma/prisma: 
	- [ ] Env vars:
	    - [ ] Add new, deprecate old: `PRISMA_SCHEMA_ENGINE_BINARY` (works the same as `PRISMA_MIGRATION_ENGINE_BINARY`)
	    - [ ] Replace: `FORCE_PANIC_MIGRATION_ENGINE` → `FORCE_PANIC_SCHEMA_ENGINE`
    - [ ] remove `stdout.replace` logic in [`getEngineVersion.ts`](https://github.com/prisma/prisma/blob/ce9b83715830981032642c72d79451e29b862b69/packages/internals/src/engine-commands/getEngineVersion.ts#L27-L31)
    - [ ] https://github.com/prisma/prisma/pull/19634
- [ ]  prisma/docs: Rename `Migration engine` (and equivalents like `migration-engine`) to `Schema engine` (and equivalents)
- [ ] prisma/docs: update https://www.prisma.io/docs/reference/api-reference/environment-variables-reference#custom-engine-file-locations
- [ ]  prisma/engineer: Rename `migration-engine` → `schema-engine`
    - [ ]  https://github.com/prisma/engineer/pull/93
- [ ]  prisma/engines: Rename `migration-engine*` crates → `schema-engine*`
    - [ ]  The only thing missing is to change the `[[bin]]` `name` property in `schema-engine/cli/Cargo.toml` from `migration-engine` to `schema-engine`
    - [ ]  https://github.com/prisma/prisma-engines/pull/3855
- [ ] anything else?

**Comment by jkomyno** [comment]
Added:
- [ ] remove `stdout.replace` logic in [`getEngineVersion.ts`](https://github.com/prisma/prisma/blob/ce9b83715830981032642c72d79451e29b862b69/packages/internals/src/engine-commands/getEngineVersion.ts#L27-L31)

**Comment by janpio** [comment]
Clarified that `PRISMA_MIGRATION_ENGINE_BINARY` needs to stick around and keep working (although deprecated) as we did not deprecate before and we don't _have_ to make all our users change that. If we want, we can also output a warning message when the old env var is used.
