### ISSUE TITLE
Prisma Client: make `fieldReference` GA

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#19379]
## Overview
- [x] Check [issues](https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3A%22topic%3A+fieldReference%22+sort%3Aupdated-desc) with `fieldReference` topic tag 
- [x] Check https://github.com/prisma/prisma/issues/15068

### To Reproduce
- [ ] https://github.com/prisma/prisma/issues/15068#issuecomment-1561782156 (@Weakky)
- [x] https://github.com/prisma/prisma/issues/16989 (haven't been able to reproduce)
- [x] https://github.com/prisma/prisma/issues/16997  
- [x] https://github.com/prisma/prisma/pull/19383
## Improvements
- [x] https://github.com/prisma/prisma/issues/19442 (does not prevent GA'ing it IMO)
- [x] https://github.com/prisma/team-orm/issues/154

## Rest
- [x] Check feature request: https://github.com/prisma/prisma/issues/18002  (does not prevent GA'ing it IMO)
- [x] Deprecate preview feature flag
	- [x] https://github.com/prisma/prisma-engines/pull/3996
	- [x] https://github.com/prisma/prisma/pull/19427
- [x] See https://github.com/prisma/prisma/pull/19893/files#r1237642889
- [ ] Inform and close https://github.com/prisma/prisma/issues/15068
- [ ] Update docs https://github.com/prisma/docs/issues/4858
- [ ] Anything else?
