### ISSUE TITLE
Prisma Client: make `orderByNulls` GA

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#19377]
Note from @Weakky: MongoDB is intentionally not supported yet because supporting the feature required too many hacks. The connector doesn't have the capability and thus doesn't expose the API at all. We could review that in the future, but I'd suggest we keep it that way for now.

- [x] Check [issues](https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3A%22topic%3A+orderByNulls%22+sort%3Aupdated-desc) with `orderByNulls` topic tag 
- [x] Check https://github.com/prisma/prisma/issues/14377
- [x] Bugs
	- [x] Confirmed 
		- [x] Implement it for MongoDB? 
			- [x] Related bug issue: https://github.com/prisma/prisma/issues/16728 - **NOT A BUG**
			- [x] And missing tests: https://github.com/prisma/prisma/issues/17100 - **NOT A BUG**
	- [x] To reproduce
		- [x] https://github.com/prisma/prisma/issues/17081
- [x] Deprecate preview feature flag
	- [x] https://github.com/prisma/prisma-engines/pull/4022 
	- [x] https://github.com/prisma/prisma/pull/19757/files
- [x] Inform and close https://github.com/prisma/prisma/issues/14377
- [x] Update docs https://github.com/prisma/docs/issues/4853
- [ ] Anything else?
