### ISSUE TITLE
Prisma Client: make `clientExtensions` GA 

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#19416]
- [x] Check [issues](https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3A%22topic%3A+clientExtensions%22+sort%3Aupdated-desc) with `clientExtensions` topic tag 
- [x] Check https://github.com/prisma/client-planning/issues/262
- [x] Check https://github.com/prisma/prisma/issues/16500

---

- [ ] Features/improvements
	- [ ] additive, can be done later https://github.com/prisma/prisma/issues/18628
	- [x] breaking, we could do before GA https://github.com/prisma/prisma/issues/18125
	- [x] https://github.com/prisma/prisma/issues/18829
	- [x] See board https://github.com/orgs/prisma/projects/112/views/18

---

- [ ] Bugs
	- [x] Confirmed
		- [x] https://github.com/prisma/prisma/issues/17405
		- [x] https://github.com/prisma/prisma/issues/17948
		- [x] https://github.com/prisma/prisma/issues/18092
		- [x] https://github.com/prisma/prisma/issues/17388
		- [x] Not a blocker: https://github.com/prisma/prisma/issues/17767
	- [ ] To reproduce
		- [x] https://github.com/prisma/prisma/issues/18182
		- [x] https://github.com/prisma/prisma/issues/17837
		- [x] https://github.com/prisma/prisma/issues/17843
		- [x] https://github.com/prisma/prisma/issues/18854
		- [x] https://github.com/prisma/prisma/issues/18276
		- [x] https://github.com/prisma/prisma/issues/18875
	- [x] To Close?
		- [x] can be closed https://github.com/prisma/prisma/issues/18300
		- [x] https://github.com/prisma/prisma/issues/7161
		- [x] https://github.com/prisma/prisma/issues/15074
---

- [ ] Docs
	- [x] Update docs
	- [ ] document limitation first https://github.com/prisma/prisma/issues/17991
	- [x] Create a how to publish an extension guide? 
		- ~Blocked by~ https://github.com/prisma/prisma/issues/18829	
	- [ ] https://github.com/prisma/prisma/issues/19112
	- [x] https://github.com/prisma/prisma/issues/18943

---

- [x] Deprecate preview feature flag
- [x] Inform and close https://github.com/prisma/prisma/issues/16500
- [ ] Anything else?

https://github.com/prisma/prisma/issues/15074
