### ISSUE TITLE
[Meta] Known Migrations that behave unexpectedly

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#2018]
A collection of migrations that result in stuck deployments or other inconsistencies.

### Stuck Deployments

* [x] https://github.com/graphcool/prisma/issues/2011
* [x] https://github.com/graphcool/prisma/issues/1894
* [x] https://github.com/graphcool/prisma/issues/2121
* [x] https://github.com/graphcool/prisma/issues/1802
* [x] https://github.com/graphcool/prisma/issues/2170
* [x] https://github.com/prismagraphql/prisma/issues/2118
* [x] https://github.com/prismagraphql/prisma/issues/2536
* [x] https://github.com/prismagraphql/prisma/issues/2793
* [x] https://github.com/prismagraphql/prisma/issues/2906
* [x] https://github.com/prisma/prisma/issues/3198
* [ ] https://github.com/prismagraphql/prisma/issues/2750 (on hold)

### Inconsistencies

* [x] https://github.com/graphcool/prisma/issues/1944
* [x] https://github.com/graphcool/prisma/issues/1687
* [x] https://github.com/graphcool/prisma/issues/1773
* [x] https://github.com/graphcool/prisma/issues/1640

### Internal Server Errors
* [x] https://github.com/graphcool/prisma/issues/1836
* [x] https://github.com/prismagraphql/prisma/issues/2871
* [x] https://github.com/prisma/prisma/issues/2927
* [x] https://github.com/prisma/prisma/issues/3239

### Misc
* [x] https://github.com/graphcool/prisma/issues/2172

**Comment by robbyemmert** [comment]
I just have to say, Prisma is a really ambitious project, and you all get a lot of credit. Automated migrations are probably the most daunting thing about building a framework like this, but keep going, I love it!

In the mean time, do you have any recommendations on how to roll back a failed migration, or is there a recommended way to write a manual migration?

Thanks!

**Comment by Weakky** [comment]
Meanwhile all these issues get solved, I advise people to never deploy without backing-up your data before, as once it happens it seems like there's no way to get out of it without `prisma reset` and changing the stage.

Adding
```json
"deploy": "prisma export -p database/seed.zip && prisma deploy"
```
to your scripts section in the `package.json` is a safe work-around for now, allowing to `prisma import` or `prisma seed` whenever you have to reset prisma.

**Comment by marktani** [comment]
Hey @robbyemmert, thanks a lot for your kind words! 🙂 

> In the mean time, do you have any recommendations on how to roll back a failed migration, or is there a recommended way to write a manual migration?

All migrations are kept in the internal database (can be called `graphcool` or `prisma`). There, a `Migration` table keeps track of all migrations.

You can cross-reference the migrations in there with the _actual_ database schema deployed for a specific service.

@Weakky, backing up your data is always a good idea 🙂You can always patch things up manually on the database level to restore API access, and the data is not affected.

**Comment by Minishlink** [comment]
Hello @marktani, I'm considering prisma for new projects, and I have to say that I'm very impressed by your work, thanks and congratulations! :)

Migration is a blocker for production though, do you have documented strategies on how to workaround possible failures when deploying with a change of schema? Or does it basically boils down to do the database migration manually and prisma will adapt automatically?

**Comment by terion-name** [comment]
Another stuck to the list #2490

**Comment by marktani** [comment]
Closing this, as all known issues have been fixed & released. Especially for `1.18.1`, we fixed a bunch of them again.

**Comment by tanujdoshi** [comment]
> Closing this, as all known issues have been fixed & released. Especially for `1.18.1`, we fixed a bunch of them again.

hello , please can you help me to solve this #4625
