### ISSUE TITLE
Split out the fix functionality of `prisma format`

### ISSUE THREAD

**Issue by Druue** [prisma/prisma#24227]
## Context
The relevant code that adds the ""fix"" functionality to `format` is in:
- [psl-core/src/reformat::enrich](https://github.com/prisma/prisma-engines/blob/2a74da1ba346c169f86c7fa6614128f697a8ce14/psl/psl-core/src/reformat.rs#L93-L112)

Which takes input from the three following functions:
- [`reformat::push_missing_fields`](https://github.com/prisma/prisma-engines/blob/2a74da1ba346c169f86c7fa6614128f697a8ce14/psl/psl-core/src/reformat.rs#L203-L209)
- [`reformat::push_missing_attributes`](https://github.com/prisma/prisma-engines/blob/2a74da1ba346c169f86c7fa6614128f697a8ce14/psl/psl-core/src/reformat.rs#L171-L177)
- [`reformat::push_missing_relation_attribute_args`](https://github.com/prisma/prisma-engines/blob/2a74da1ba346c169f86c7fa6614128f697a8ce14/psl/psl-core/src/reformat.rs#L120-L130)

Instead of automatically being applied through format, we should offer the separate ability to fix the issues this catches. We have diagnostics for two of these already (they aren't used, however, in the current implementation of fixes in format)

- [missing 1:m](https://github.com/prisma/prisma-engines/blob/2a74da1ba346c169f86c7fa6614128f697a8ce14/psl/psl-core/src/validate/validation_pipeline/validations/relations/one_to_many.rs#L18-L23)
- [missing 1:1](https://github.com/prisma/prisma-engines/blob/2a74da1ba346c169f86c7fa6614128f697a8ce14/psl/psl-core/src/validate/validation_pipeline/validations/relations/one_to_one.rs#L19-L24)

![image](https://github.com/prisma/prisma/assets/29753584/9638e1c2-b720-435a-bb6b-cc75fc511055)

As this is a breaking change, we should look at the following intermediary changes first
```[tasklist]
### Temporary
- [ ] add separate `prisma fix`
- [ ] add separate `prisma format-only`
```

```[tasklist]
### Tasks
- [ ] Discovery: [how do we want to incorporate `prisma fix` into the CLI](https://prisma-company.slack.com/archives/C058VM009HT/p1715883155091239)
- [ ] Add any missing diagnostics
- [ ] Update the diagnostics we use in engines to be LSP compatible
- [ ] Offer code actions to perform the fixes that are currently done in `format`
```

[Related Notion Page](https://www.notion.so/prismaio/Clean-up-prisma-format-problem-space-2c0489fd4dd0499ab0bdc5b96e3b22bb)

**Comment by Druue** [comment]
related issues:
- https://github.com/prisma/language-tools/issues/91

**Comment by jwueller** [comment]
As a user I consider this a bug, since formatting modifying the semantics is extremely unexpected and dangerous.

And if you consider it a bug too, I wouldn't consider fixing the bug to be a breaking change, since it wasn't desired behavior to begin with.

I'd even argue that it's impossible to automatically "fix" these issues at all, since the fix isn't unambiguous. It has to guess what the user actually intended, which will be wrong half of the time.

Honestly, just get rid of it entirely and only produce linting errors. Conflicts need to be resolved manually.
