### ISSUE TITLE
[EPIC] Re-Introspection

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2829]
We want to remove one of the remaining big pain points of Introspection: If you manually adjusted your data model after introspection (to rename fields or models, or add default IDs for example) these changes are currently lost once you introspect again ("re-introspect", for example, because your database was changed manually or migrated by another tool).

This project consists of many individual problems that we are tackling one by one:

- [x] https://github.com/prisma/prisma/issues/2503: Keep manual changes to relation field names
- [x] https://github.com/prisma/prisma/issues/2545: Keep `@map` and `@@map`
- [x] https://github.com/prisma/prisma/issues/2534: Keep defaults that are not persisted in the database
- [x] https://github.com/prisma/prisma/issues/1997: Keep order of models of existing Prisma schema
- [x] https://github.com/prisma/prisma/issues/2968: Keep order of fields of existing Prisma schema
- [x] https://github.com/prisma/prisma/issues/3052: Keep comments in schema
- [x] https://github.com/prisma/prisma/issues/3335: Keep `@updatedAt`

We might also decide that some of them are not worth the effort.

Some more issues are listed related to this under: https://github.com/prisma/prisma/labels/topic%3A%20re-introspection

**Comment by janpio** [comment]
With 2.1.0 we shipped the _experimental flag_ `--experimental-reintrospection`  that can be used in `npx prisma introspect --experimental-reintrospection`. Behind that flag we implemented the first two pieces of Re-Introspection, https://github.com/prisma/prisma/issues/2503 and https://github.com/prisma/prisma/issues/2545

**Comment by kennytraction** [comment]
Thanks for putting the effort into this feature. It is greatly appreciated!

We have only had a few issues with re-introspection:
- Renamed relations which is fixed and working in v2.1.1
- `@updatedAt` is not maintained. I thought there was an issue for this but I can't seem to find it now. Similar to the `@map` issue.
- Error with renamed relations to the same table. I have created an issue and explained it here: https://github.com/prisma/prisma/issues/2844

**Comment by janpio** [comment]
I tested `--experimental-reintrospection` on the database @nikolasburk posted in another issue, where he used `@@map` and renamed relation fields: https://github.com/prisma/prisma/issues/2425#issuecomment-649709485 All changes were kept 🚀

**Comment by theneshofficial** [comment]
So far it works great for model classes. It would be great if can keep the changes made to enum class name as well.

**Comment by Akxe** [comment]
When using ` --experimental-reintrospection` flag, I got `[introspection-engine\connectors\sql-introspection-connector\src\re_introspection.rs:346:25] called 'Option::unwrap()' on a 'None' value` error, without it, it run as expected.

**Comment by janpio** [comment]
Can you please create a new issue @Akxe and include the full schema and information we need to reproduce this? Thanks.

**Comment by Akxe** [comment]
@janpio Here you go! https://github.com/prisma/prisma/issues/2893

**Comment by ExiaSR** [comment]
When using the reintrospection when the schema is located in a custom directory, the `dotenv` from the same directory is not read by the Prisma CLI.

https://github.com/prisma/prisma/issues/2924

**Comment by janpio** [comment]
Quick update: 

We just merged the last planned feature here 🚀 

If you install the `dev` version with `npm install @prisma/cli@dev` you will get the state we are planning to launch with 2.6.0 as part of the `prisma introspect` functionality. Further improvement would be merged into the main feature then in the future directly if we find anything else to do.

For now you can still test it with: `npx prisma introspect --experimental-reintrospection`

It would be great if you all could test this again, before we go into the final integration with https://github.com/prisma/prisma/issues/3331 and see if your use cases are covered now - and let us know if not.

(Pinging some people from this and other related issues for visibility: @Akxe @ExiaSR @theneshofficial @kennytraction @theRocket @louisrli @harryttd)

**Comment by bkrausz** [comment]
Sounds like you're on the tail end of dev work here, but any chance of getting eyes on #3076? tl;dr - reintrospection is incorrect in a particularly bad way when using partial unique indexes, having Prisma ignore them rather than incorrectly assume they're globally unique would be a large improvement in usability for us.

**Comment by janpio** [comment]
@kennytraction Ahem, there should be a `2.6.0-dev.11` now - seems I was to quick to post here.

**Comment by kennytraction** [comment]
> @kennytraction Ahem, there should be a `2.6.0-dev.11` now - seems I was to quick to post here.

No problem. With that build it seems all of our issues have been addressed. 

Thanks!

**Comment by janpio** [comment]
Finished via https://github.com/prisma/prisma/pull/3445 which closed https://github.com/prisma/prisma/issues/3331 🚀
