### ISSUE TITLE
EPIC: Support constraints and indexes with names that have invalid characters in Javascript

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#3193]
## Problem

Right now if you have the following schema:

```prisma
model A {
  a  Int
  b  Int
  @@unique([a, b], name: "no-dupes")
}
```

You'll end up with a generated client with syntax errors. This is because we use the `name` of `@@unique` in our generated code. In Javascript, you can't have identifiers with a dash (e.g. `-`).

This problem also applies to our other constraints like `@@id` and `@@index`. For `@@index`, we don't currently expose the name to the client so it's not a problem for us yet (and it may never be).

## Suggested solution

Similar to our `@map()` at the field level, we could introduce:

```
@@unique([a, b], name: "noDupes", map: "no-dupes")
```

In this case `name` could be optional since its final form would be dependent on the language.

As for which characters should we add map to, I think most languages have a fairly standard concept of identifiers. We could allow names `[A-Za-z][A-Za-z0-9]*` without map, every other name gets a map.

## Alternatives

It might also make sense to be more precise and investigate our usage of `@@id`, `@@unique`. If we're using them as keys, we could get away with adding quotes around them. For example, `{ "no-dupes": ... } ` is valid Javascript syntax.

Another idea that would also solve this issue: https://github.com/prisma/prisma/issues/4010

## Engine Tasks

- [x] https://github.com/prisma/prisma-engines/issues/1037
- [x] https://github.com/prisma/prisma-engines/issues/1038
- [x] https://github.com/prisma/prisma-engines/issues/1039
- [x] https://github.com/prisma/prisma-engines/issues/1040

## References

- Community Issue: #2393.
- More discussion about the problem: https://prisma.slack.com/archives/CCWDULGUW/p1613539035068300

**Comment by mavilein** [comment]
Sub Tasks:
- [Datamodel Parser](https://github.com/prisma/prisma-engines/issues/1037)

**Comment by janpio** [comment]
Issue https://github.com/prisma/prisma/issues/3964 reported the exact same problem and was closed as a duplicate of this - but includes a great real world example that came from just using Prisma.

**Comment by pantharshit00** [comment]
Another good example: https://github.com/prisma/prisma/issues/4182

**Comment by matthewmueller** [comment]
This would be solved by: https://github.com/prisma/prisma/issues/4010. We could bundle these issues together.

**Comment by mavilein** [comment]
related: https://github.com/prisma/prisma-engines/issues/962

**Comment by matthewmueller** [comment]
Please double-check that this issue is resolved before closing this issue: https://github.com/prisma/prisma-client-js/issues/949

**Comment by do4gr** [comment]
This is now available via the `namedConstraints` preview flag since 2.29. See https://www.prisma.io/docs/guides/upgrade-guides/upgrading-to-use-preview-features/enabling-named-constraints
