### ISSUE TITLE
Migrate to `npx prisma` Epic

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#4488]
## Problem

The `npx prisma` command changes between Prisma 1 and Prisma 2 depending on how your machine is setup.

1. If you run `npx prisma` on a project with `@prisma/cli` already installed, you get Prisma 2.
2. If you run `npx prisma` on a fresh project with nothing installed, you may get Prisma 1 or 2.
    - If you do not have any `prisma` binary in your `$PATH`, you'll get Prisma 1
    - If you do have a `prisma` binary in your `$PATH`, you'll get either Prisma 1 or Prisma 2, depending on what that binary points to.

**These rules aren't obvious.** To make matters worse, if you're expecting Prisma 2 and you get Prisma 1, you get a CLI that shows Data workflows and Cloud options. This gives an initial false impression of the capabilities of Prisma 2.

Another example of this problem is by looking at our [quickstart](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-prisma-migrate-typescript-postgres#create-project-setup).  We're very careful to run `npm install @prisma/cli` before running `npx prisma`. If you run these commands the other way around, you'll likely end up with Prisma 1.

### Stage 2

- [ ] Publish one last update to the 1.x.x version of `prisma` to prevent update-notifier from showing warnings 2.x releases. Show 1.x updates. [Issue]() 
    - This work should be time-boxed as it's part of the [risks we're trying to mitigate](https://www.notion.so/prismaio/Improve-npx-prisma-6a013e123d824e329f2f29f58e96da72#6cc9cc9ce943401192517ea005434550).
- At this point we have done a bit more prep work, but we haven't committed ourselves to this transition. We could stop working and nobody would notice. After crossing this line, Prisma 1 users will likely notice the transition.

### Stage 3

- [ ]  Update the Prisma 2 update notifier in the CLI to [support the checkpoint server's upcoming changes](https://www.notion.so/prismaio/Improve-npx-prisma-6a013e123d824e329f2f29f58e96da72#ec859000738e4b2987ab91ef14660fb3)
- [ ]  Add detection to CLI for Prisma 1 projects (if they have a `prisma.yml`) and warn them that they might want to install the [1.x version published above.](https://www.notion.so/prismaio/Improve-npx-prisma-6a013e123d824e329f2f29f58e96da72#ecb9bf3675af42dcae54a8aabaceaa8a)
    - This work should be time-boxed as it's part of the [risks we're trying to mitigate](https://www.notion.so/prismaio/Improve-npx-prisma-6a013e123d824e329f2f29f58e96da72#6cc9cc9ce943401192517ea005434550).
- [ ]  Start publishing over Prisma 1. `npm publish prisma@2.x.x`. This will change what `npm install prisma` does - it now gives you Prisma 2 instead of Prisma 1.
- Up to this point, we still haven't turned on the Prisma 2 firehose. Prisma 1 users will have been affected, but Prisma 2 users are unaware of this transition.
- [ ]  Update our documentation, blog posts, everywhere else to use `npm install prisma` instead of `npm install @prisma/cli`
    - `npm install prisma` is good practice in quick-start regardless (vs. `npx prisma`)
- [ ]  Change our checkpoint server's update notification to instruct people to:
    1. Run `npm install prisma` instead of `npm install @prisma/cli`
    2. Run `npm uninstall @prisma/cli`
    - Careful, this also requires changes in the CLI as it is not just showing a server side string any more but creating the string locally (using information about npm vs. yarn for example). See the [first TODO in Stage 3.](https://www.notion.so/prismaio/Improve-npx-prisma-6a013e123d824e329f2f29f58e96da72#6b1c60ac36f04eb5bd392c6ff8868197)
- [ ]  Publish a final version of `@prisma/cli` that tells people to install the `prisma` package instead
    - Because we want people do this immediately, `@prisma/cli` will tell users to use `npm install prisma` (and possible `npm uninstall @prisma/cli` if present) from now on and exit immediately going forward.
- [ ]  Remove `@prisma/bar`
