### ISSUE TITLE
EPIC: Implement errors spec

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#618]
Implementation of https://github.com/prisma/specs/issues/113

Phase 1: Spec ready for review

- [x] Basic error messages/codes to be modified as per the spec https://github.com/prisma/prisma2/issues/719
- [x] Handling unknown errors (telemetry) and Error masking https://github.com/prisma/prisma2/issues/721
- [ ] Permalinks for error codes https://github.com/prisma/prisma2/issues/718
- [ ] Document https://github.com/prisma/prisma2/issues/609
- [x] Meta schema object (for Programmatic consumption of errors) https://github.com/prisma/prisma2/issues/720
