### ISSUE TITLE
Preview feature feedback: Node-API support (`nApi`)

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#6301]
Please share your feedback about the `nApi` functionality released in [v2.20.0](https://github.com/prisma/prisma/releases/tag/2.20.0) in this issue.

- If you encounter a bug, please [open a bug report](https://github.com/prisma/prisma/issues/new?assignees=&labels=&template=bug_report.md&title=) in this repo. 
- If the feature is working well for you, please share this in a comment below or leave a 👍 on this issue.

If you have any questions, don't hesitate to ask them in the [`#prisma-client`](https://prisma.slack.com/archives/CCWDULGUW) channel in the [Prisma Slack](https://slack.prisma.io).

### Known Limitations

- [x] (**Resolved**) You can't have more than one instance of the Prisma Client yet, so this will not work properly:
    ```js
    const prisma1 = new PrismaClient()
    const prisma2 = new PrismaClient()
    ```
- [x] (**Resolved**) Currently, logging queries does not work with Node-API and Jest ([Issue](https://github.com/prisma/prisma-engines/issues/1877)). For example, the following will not output any query logs. (_Note_: This seems to only be the case when using jest)
	```ts
	const prisma = new PrismaClient({
	  log: ['query']
	})
	```
- [x] (**Resolved**) Node-API libraries do not work with process mocking of Jest ([issue](https://github.com/prisma/prisma/issues/7562))
- [x] Node-API does not work on M1 ARM Macs, Apple Silicon ([issue](https://github.com/prisma/prisma/issues/7387))
- [ ] Node-API does not work on 32bit Node ([issue](https://github.com/prisma/prisma/issues/6905))

**Comment by pimeys** [comment]
Follow-up ticket for the issue with more than one engines: https://github.com/napi-rs/napi-rs/issues/518

**Comment by Akxe** [comment]
@matthewmueller Why would anyone want 2 instances of PrismaClient?

**Comment by pimeys** [comment]
@Akxe we have one test at least that utilizes them, and we found the issues from that test...

**Comment by janpio** [comment]
Because you would want to connect to two different databases, or connect to the same database with different timeouts, some other configuration and so on @Akxe - multitude of reasons really. Not very common, but we wanted to document that these use cases could currently be problematic.

**Comment by Akxe** [comment]
Thanks for sharing tips, i do really appreciate that 😊

**Comment by pantharshit00** [comment]
> You can't have more than one instance of the Prisma Client yet, so this will not work properly:

I think this is lifted now with napi PR merged.

**Comment by P4sca1** [comment]
I think I encountered a memory leak when using the `napi` preview feature.
I deployed a new version updating prisma from 2.19.x to 2.21.x and enabling the napi preview feature in the middle of the graph. The graph shows the last 12 hours.
![Bildschirmfoto 2021-04-30 um 19 54 57](https://user-images.githubusercontent.com/10992664/116734833-053b1200-a9ee-11eb-8564-d36b61f607d9.png)
The node process got killed multiple times as you can see and then started to eat up all the memory again.

I deployed a new version, which changed nothing but removed the `napi` preview feature and I dont see this behaviour anymore.
![Bildschirmfoto 2021-04-30 um 19 57 34](https://user-images.githubusercontent.com/10992664/116735107-5e0aaa80-a9ee-11eb-825a-14805b70fcc8.png)
At the time in the graph (last 15 minutes) where the memory usage drops, the new version got deployed. From that point in time, the usage was consistent again. Before the memory usage grew constantly.

**Comment by pimeys** [comment]
Yep. Fixed in the latest dev versions. And next Tuesday's 2.22.0. It's not N-API, but how the logger works in that side of our codebase.

**Comment by carlitorweb** [comment]
When I enable it adding `previewFeatures = ["napi"]` and run after `npx prisma db push --preview-feature` the process stuck at: **Running generate...**. If I remove _napi_ then all run okay again.

**Comment by pimeys** [comment]
@carlitorweb I can't reproduce this.

Prisma version: 2.21.0
OS: NixOS

My datamodel:

```prisma
datasource db {
  provider = "postgresql"
  url      = "postgres://postgres:prisma@localhost:5435/postgres"
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["napi"]
}

model A {
  id Int @id @default(autoincrement())
  a String
}

model B {
  id Int @id @default(autoincrement())
  b String
}
```
I ran the command:
```bash
❯ npx prisma db push --preview-feature
Environment variables loaded from .env
Warning Precompiled binaries are not available for nixos.
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "localhost:5435"

The database is already in sync with the Prisma schema.

Running generate... (Use --skip-generate to skip the generators)
Warning Precompiled binaries are not available for nixos.
✔ Generated Prisma Client (2.21.1) to ./node_modules/@prisma/client in 63ms
```
Which exited and generated the client correctly. Can you share more info about your environment?

**Comment by pimeys** [comment]
What we found out last week is that the N-API version will not work with the 32bit node.js on Windows. Please chime in and comment on this issue for discussion and monitor the progress: https://github.com/prisma/prisma/issues/6905

**Comment by carlitorweb** [comment]
@pimeys Testing again just now:

Prisma version: 2.21.2
OS: LTS Ubuntu

**The datamodel where I testing it:**

```js
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["napi"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Posts {
  id        Int      @id @default(autoincrement())
  title     String
  content   String   @db.VarChar(500)
  creator   User     @relation(fields: [authorId], references: [id])
  authorId  Int
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model User {
  id       Int     @id @default(autoincrement())
  posts    Posts[]
  name     String
  email    String  @unique
  password String
  status   String  @default("I am new!")
}
```

**Using nodejs LTS:**

`npx prisma db push --preview-feature`

```shell
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "apicourse", schema "public" at "localhost:3306"

The database is already in sync with the Prisma schema.

Running generate... (Use --skip-generate to skip the generators)
```

**The process stuck there....** 

------

**Comment by pimeys** [comment]
Hmm... I just checked it with your datamodel and against MySQL 5.7. Everything works.

```bash
❯ node --version
v14.16.0
```

**Comment by carlitorweb** [comment]
Not sure what could be wrong here then for me. Except for the models, what other thing should I check?

**Comment by janpio** [comment]
Can you run `prisma generate` manually when you have `napi` enabled? It is stuck not on the migration part, but then it later runs `generate` under the hood @carlitorweb

**Comment by carlitorweb** [comment]
Okay, I will do it. In case is relevant, I have this .env

```sh
NODE_ENV="development"
DEBUG="*"
```

**Comment by janpio** [comment]
Discussion moved to https://github.com/prisma/prisma/issues/6926

**Comment by vjpr** [comment]
Preview feature flags are case-sensitive.

Docs are wrong: https://www.prisma.io/docs/concepts/components/prisma-engines/query-engine#enable-the-n-api-preview

```
Error: Schema Parsing P1012

Get config 
error: The preview feature "nApi" is not known. Expected one of: microsoftSqlServer, groupBy, createMany, orderByRelation, napi
  -->  schema.prisma:3
   | 
 2 |   provider = "prisma-client-js"
 3 |   previewFeatures = ["nApi"]
   | 

Validation Error Count: 1

```

**Comment by janpio** [comment]
The feature flag got renamed when we made them case insensitive (which was triggered by us using two different spelling of `nApi` in different places. So this should not be an issue any more at all @vjr.

**Comment by vjpr** [comment]
Is there a way to disable NAPI without regenerating the client?

**Comment by pantharshit00** [comment]
@vjpr What is your usecase for that?

**Comment by vjpr** [comment]
Compare performance.

**Comment by pantharshit00** [comment]
You can generate two client for that like so:
```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["nApi"]
  output          = "./client1"
}

generator client2 {
  provider = "prisma-client-js"
  output   = "./client2"
}
```

Then you can compare performance. If you trying this in an existing app, then I don't think we have an option for that.

**Comment by pantharshit00** [comment]
Also, word of caution that NAPI is still in preview. We just merged fixed for many memory leaks today itself. So results might change.

**Comment by vjpr** [comment]
After testing 1000 queries with 100 currency ([`p-times`](https://github.com/sindresorhus/p-times)), I'm seeing a big perf regression:

with napi: 420ms 
without napi: 178ms

**Comment by pantharshit00** [comment]
Did you use the dev version?

**Comment by vjpr** [comment]
I installed `prisma@dev` and now I get `Error: Invalid or unexpected token` when reading my schema.

**Comment by pantharshit00** [comment]
I can reproduce that. Looks like it got broken when https://github.com/prisma/prisma/pull/7152 was merged today.

cc @williamluke4

**Comment by williamluke4** [comment]
Hey @vjpr, Yep this is a bug, there's a fix incoming but you should be able to work around this by using 
```PRISMA_FORCE_NAPI=true pnpx prisma generate```

**Comment by williamluke4** [comment]
This should be solved in the lastest `dev` version

**Comment by vjpr** [comment]
@williamluke4 Thanks, works.

With latest `dev` version, with high concurrency it's still twice as slow per query compared to without napi.

I will look at publishing my ORM benchmarking library today if you want to see.

**Comment by pimeys** [comment]
How do you measure. I just did a tight loop:

```javascript
import { PrismaClient } from '@prisma/client'

const metrics = require('metrics');
const prisma = new PrismaClient();

function now() {
  var hrTime = process.hrtime();
  return hrTime[0] * 1000000 + hrTime[1] / 1000;
}

async function main() {
  let histogram = new metrics.Histogram();

  var report = new metrics.Report();
  report.addMetric('queryTime', histogram);

  var reporter = new metrics.ConsoleReporter(report);
  reporter.start(1000);

  while (true) {
    var start = now();
    const all = await prisma.a.findMany({
      include: {
        bs: true,
      },
    });
    histogram.update(now() - start);
  }
}

main()
  .catch((e) => {
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  })
```
And results:
```
With N-API ---------------------------------------------------------------------
queryTime
             count = 99550
               min = 261.12
               max = 72612.98
              mean = 319.68
            stddev = 241.98
              50% <= 310.25
              75% <= 326.76
              95% <= 368.96
              98% <= 378.14
              99% <= 389.39
            99.9% <= 1219.91

Without N-API ---------------------------------------------------------------------
queryTime
             count = 4336
               min = 499.38
               max = 107903.64
              mean = 7600.22
            stddev = 15235.63
              50% <= 667.22
              75% <= 785.09
              95% <= 40940.40
              98% <= 40997.68
              99% <= 41613.17
            99.9% <= 42778.98
```
Numbers are in microseconds. If there is a specific query that is slow, file an issue. I also must underline here that our priority with N-API is not performance, but simplifying the codebase and closing that extra TCP port the engine binary opens up.

**Comment by janpio** [comment]
@vjpr @pimeys Please open a new issue for this discussion about the Napi performance so we can properly track and tackle that. Thank you.

**Comment by vjpr** [comment]
@pimeys Your example is only testing sequential runs. I'm using [`p-times`](https://github.com/sindresorhus/p-times) to run concurrent queries.

**Comment by pantharshit00** [comment]
@vjpr I am getting the following results with concurrency via p-times:
```ts
import { PrismaClient } from "@prisma/client";
import { performance } from "perf_hooks";
import metrics from "metrics";
import pTimes from "p-times";

const prisma = new PrismaClient();
async function main() {
  let start, finish;
  let histogram = new metrics.Histogram();
  let report = new metrics.Report();
  report.addMetric("queryTime", histogram);
  let reporter = new metrics.ConsoleReporter(report);
  reporter.start(1000);

  while (true) {
    start = performance.now();
    await pTimes(1000, () =>
      prisma.test.findUnique({
        select: {
          id: true,
          name: true,
        },
        where: {
          id: 1,
        },
      })
    );
    finish = performance.now();
    histogram.update(finish - start);
  }
}

main();
```

Results:
```
without NAPI---------------------------------------------------------------------
queryTime
             count = 575
               min = 34.03
               max = 222.30
              mean = 80.25
            stddev =  7.58
              50% <= 79.95
              75% <= 80.22
              95% <= 81.05
              98% <= 89.62
              99% <= 90.25
            99.9% <= 222.30
NAPI---------------------------------------------------------------------
queryTime
             count = 566
               min = 29.16
               max = 115.68
              mean = 76.30
            stddev =  7.10
              50% <= 79.59
              75% <= 80.06
              95% <= 80.95
              98% <= 89.92
              99% <= 90.32
            99.9% <= 115.68
```

This doesn't indicate a regression. Can you try this test out? 

Version used:
```
Environment variables loaded from prisma\.env
prisma               : 2.24.0-dev.34
@prisma/client       : 2.24.0-dev.34
Current platform     : windows
Query Engine         : query-engine 3e7fd9395fd522da21025ecfd731803bae72fd2f (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 3e7fd9395fd522da21025ecfd731803bae72fd2f (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 3e7fd9395fd522da21025ecfd731803bae72fd2f (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 3e7fd9395fd522da21025ecfd731803bae72fd2f (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 3e7fd9395fd522da21025ecfd731803bae72fd2f
Studio               : 0.397.0
```

Schema:
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model test {
  id   Int    @id @default(autoincrement()) @db.Integer
  name String @db.Text
}

```


So can you please try this once again or maybe share the benchmark code which detects the regression.

**Comment by Sytten** [comment]
> After testing 1000 queries with 100 currency ([`p-times`](https://github.com/sindresorhus/p-times)), I'm seeing a big perf regression:
> 
> with napi: 420ms (findMany) 200ms (queryRaw)
> without napi: 178ms (findMany) 100ms (queryRaw)
> 
> Using `chinook` sample database and `select * from customers`.

@pantharshit00 he said that above, I will check myself today. My guess would be the issue is related to the size of the dataset and how NAPI handles findMany with many hundred (maybe thousand) objects.

**Comment by vjpr** [comment]
@pantharshit00 Will try your benchmark script to see I can replicate.

@Sytten I am running on https://github.com/lerocha/chinook-database (see https://github.com/morenoh149/postgresDBSamples/issues/1#issuecomment-455454533 for an error that you need to work around when importing it)

**Comment by vjpr** [comment]
@pantharshit00 You need to add concurrency with pTimes

```
await pTimes(async () => {
  await ...
}, {concurrency: 100})
```

**Comment by pimeys** [comment]
Out of interest, what is the `connection_limit` when your `concurrency` is 100? If much less than that, you're basically just measuring the waiting time to get a connection from the database. I'd try lowering the `concurrency` to the same value as the `connection_limit` is (default: number of logical cores + 1).

**Comment by vjpr** [comment]
`max_connections` is 100.

Other ORMs using `pg` and `pg-native` don't have this issue.

**Comment by janpio** [comment]
Pleeeeease stop using this issue for this discussion and open a new issue @vjpr. Each time all people that were involved here before get a notification.

**Comment by vjpr** [comment]
@janpio I was only responding to *your employees* asking me further questions on this thread. I was happy to close the discussion when I wrote this comment: https://github.com/prisma/prisma/issues/6301#issuecomment-851436351

I will put together a proper repro when I have time to fill out your issue template.

**Comment by janpio** [comment]
A discussion about possible performance regressions when using concurrency was split into https://github.com/prisma/prisma/issues/7382. @vjpr will also open an additional issue when he has time to get to a reproduction and link to it here.

**Comment by pimeys** [comment]
Throughput solved in latest dev.

**Comment by k-sae** [comment]
Originally posted here: #5792.

I had a major performance drawback when I was migrating from sequelize and seems the `nApi` solved it for me.
Here are the details:

**Environment**
```
os: Linux (5.10.42-1-MANJARO)
DB: MySQL (10.4.19-MariaDB)
Node: v16.3.0
prisma: 2.25
```
** Prisma schema**:
```prisma
model employees {
  emp_no       Int              @id
  birth_date   DateTime         @db.Date
  first_name   String           @db.VarChar(14)
  last_name    String           @db.VarChar(16)
  gender       employees_gender
  hire_date    DateTime         @db.Date
}
```

DB: [employees_db](https://dev.mysql.com/doc/employee/en/)

**Code**:
```javascript
for (let index = 0; index < 2000; index++) {
    const employees = await prisma.employees.findMany({
      take: 100
    })
}
```

**Results**:
```
prisma: 42.497s
nApiPrisma: 6.146s
```

Full code here: [https://github.com/k-sae/employees_prisma](https://github.com/k-sae/employees_prisma)

**Comment by SynergyEvolved** [comment]
I receive the following warnings that only appear when enabling nApi: 

`(node:4760) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 beforeExit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4760) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:4760) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:4760) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGUSR1 listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:4760) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGUSR2 listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:4760) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit`

**Comment by pimeys** [comment]
@SynergyEvolved could you share a bit more about your environment and how are you initializing Prisma? I haven't been able to reproduce these warnings yet, but it will get easier if we get a good reproduction.

**Comment by janpio** [comment]
And in a new issue please @SynergyEvolved. What might also be interesting is to know how you instantiate PrismaClient in your app. This is a Node level error message, so we at least know it is not in the Node-API library, but how we use it.

**Comment by SynergyEvolved** [comment]
> And in a new issue please @SynergyEvolved. What might also be interesting is to know how you instantiate PrismaClient in your app. This is a Node level error message, so we at least know it is not in the Node-API library, but how we use it.

I have created an issue here: https://github.com/prisma/prisma/issues/8055

**Comment by 2color** [comment]
Closing this now that this has been released to General Availability in the [3.0.1 release](https://github.com/prisma/prisma/releases/tag/3.0.1)
