### ISSUE TITLE
FD: Float & Decimal Epic

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#6902]
We have a number of issues around floats and decimals. 

**Problem 1) Precision issues**

Tighten up the query engine's acceptable inputs. Don't accept numbers and strings for decimal types, instead require clients to always send the right serialized type. Hopefully this will avoid casting floats to decimals where precision is lost.

- [x] https://github.com/prisma/prisma/issues/6852
- [x] https://github.com/prisma/prisma/issues/5925

**Problem 2) queryRaw returns the wrong number**

- [x] https://github.com/prisma/prisma/issues/6818

### Tasks

- [ ] TODO break down further.

### References

- Consider later: https://github.com/prisma/prisma/issues/7158
- Future Idea: Generate runtime bounds checks, e.g. `(if input.cost > MAX_INTEGER) throw new Error("out of bounds")`
- We have an [internal document](https://www.notion.so/prismaio/Prisma-and-float-ish-values-229744aadd634c3eb4c66eebaeda9929) which goes into more specifics.
