### ISSUE TITLE
RWC: Reserved Word Clashes Epic

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#7963]
## Problem

We have a number of issues around user input clashing with generated types. We should look into these issues holistically and try to solve them once and for all instead of playing whack-a-mole.

## Known Issues

- [x] https://github.com/prisma/prisma/issues/6580
- [x] https://github.com/prisma/prisma/issues/7162
- [x] https://github.com/prisma/prisma/issues/7655
- [x] https://github.com/prisma/prisma/issues/8153
- [x] https://github.com/prisma/prisma/issues/7518
- [x] https://github.com/prisma/prisma/issues/10490
- [x] https://github.com/prisma/prisma/issues/9307

Or via label: https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3A%22topic%3A+reserved+words%22

**Comment by pantharshit00** [comment]
I think https://github.com/prisma/prisma/issues/8153 can also be taken into this.

**Comment by matthewmueller** [comment]
Unable to repro on engines side, probably a typescript issue.

**Comment by darklight9811** [comment]
@matthewmueller  Move reserved keywords into `_key` or `$key` scope to allow users to use their names. Having an issue because my domain rule can't accept another name besides key without looking really silly :/

**Comment by SevInf** [comment]
All issues, mentined in this epic are fixed by now and the fixes will be available in Prisma 5.1. Closing the epic now.

**Comment by dmnyk** [comment]
Model name for ReturnType might also have an issue.
