### ISSUE TITLE
MDBE: MongoDB Embedded Document Support

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#8272]
## Problem

One of the major features of MongoDB is how you can store embedded data within a record. MongoDB also offers rich querying capabilities to work with this data.

Currently the Prisma Client supports writing embedded documents with the Json type

```prisma
model User {
  name String
  address Json
}
```

```typescript
prisma.user.create({
  data: {
    name: "Alice"
    address: {
      street: "1234 Wonderland Ave"
      zip: "12351"
    }
  }
})
```

Unfortunately this isn't type-safe. Nothing stops you from adding another random field to the address or writing "street" as "st".

Additionally, we currently only support a few operations on the Json type for MongoDB.

## Definition of success

- You're able to store typed embedded data within a record
- You're able to use the same read and write operations we already support on normalized relations for embedded relations
- You're able to make embedded data in an existing MongoDB database conform to a type-safe schema
- You're able to add, remove and change the embedded schema over time with some way to migrate the data to this new schema.

Achieving these outcomes may take many iterations. It's best if we create an incremental path forward that we can slice into meaningful releases.

## Tasks

- [ ] Finalize the API Design
- [ ] Share the design with the community
- [ ] Break down the feature into concrete tasks

## References

- Community Issue: https://github.com/prisma/prisma/issues/6708

**Comment by matthewmueller** [comment]
Closing in favor of: https://github.com/prisma/prisma/issues/8788
