### ISSUE TITLE
P3: Next major version Epic

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#8628]
# Situation

Prisma is adopting Semver to provide clearer expectations about upgrade compatibility. Our next major release will be Prisma 3. This epic is for gathering issues we'd like to complete prior to releasing Prisma 3. 

# Issues

### Turn Node-API on by Default (Must Have)

We'd like to make Node-API the default interface between the Typescript client and the Query Engine. These issues were pulled from our [internal project board](https://github.com/orgs/prisma/projects/50).

- [x] prisma/prisma#8731
- [x] #8839
- [x] https://github.com/prisma/docs/issues/1895
- [x] https://github.com/prisma/prisma/issues/6301

### Stabilize `referentialActions` (Must Have)

- [x] #8633
- [x] https://github.com/prisma/prisma/issues/7816

### Stabilize `namedConstraints` (Must Have)

- [x] https://github.com/prisma/migrations-team/issues/264
- [x] implement named default constraints for SqlServer
- [x] https://github.com/prisma/prisma-engines/pull/2199
- [x] https://github.com/prisma/migrations-team/issues/247 (stretch goal)
- [x] https://github.com/prisma/prisma/issues/8616

### Promote SQL Server to Generally Available (Must Have)

We're planning to promote our SQL Server for the Prisma 3 launch. The following issues were pulled from our [internal project board](https://github.com/orgs/prisma/projects/48).

- [x] https://github.com/prisma/prisma/issues/8058
- [x] https://github.com/prisma/tiberius/issues/165
- [x] https://github.com/prisma/docs/issues/1957
- [x] https://github.com/prisma/prisma/issues/4537
- [x] https://github.com/prisma/prisma/issues/4039

### Deprecate the `prisma introspect` command in favor of `prisma db pull` (Must Have)

- [x] https://github.com/prisma/docs/issues/2115
- [x] https://github.com/prisma/prisma/issues/8078

### Fix `$queryRaw` SQL Injection (Must Have)

We'd like to take this opportunity to fix a footgun in our API where it's really easy to accidentally make your application susceptible to SQL injections.

- [x] https://github.com/prisma/prisma/issues/7142
- [x] #8808
- [x] ~#8809~ 
  -  **Update Sept 3rd**: We won't have time to make this codemod, this will be an easy find and replace anyway.

### JSON Null Equality Breaking Changes (Must Have)

- [x] https://github.com/prisma/prisma/issues/8399
- [ ] https://github.com/prisma/prisma/issues/7836

### Release Pipeline Adjustments (Must Have)

- [x] https://github.com/prisma/prisma-private/issues/147

### Rework `db seed` (Must have)

- [x] https://github.com/prisma/prisma/issues/8732
- [x] Review and merge https://github.com/prisma/prisma/pull/8146
- [x] Update docs https://github.com/prisma/docs/pull/2161
- [x] QA db seed
- [x] https://github.com/prisma/prisma/issues/8033 
- [x] e2e https://github.com/prisma/e2e-tests/issues/1806
- [ ] Update https://github.com/prisma/prisma/issues/5161
- [ ] Close issues and let users know that they can use the new version https://github.com/prisma/prisma/issues?q=is%3Aissue+label%3A%22topic%3A+db+seed%22+is%3Aopen

### Stabilize `orderByRelation` (Nice to Have)

We'd like to promote `orderByRelation` from preview to generally available.

- [x] https://github.com/prisma/prisma/issues/8036
- [x] https://github.com/prisma/prisma/issues/7331
- [x] #8629
- [x] https://github.com/prisma/prisma/issues/5438

### Stabilize `orderByAggregateGroup` (Nice to Have)

We'd like to promote `orderByAggregateGroup` from preview to generally available.

- [x] #8630
- [x] https://github.com/prisma/prisma/issues/6545

### Stabilize `selectRelationCount` (Nice to Have)

We'd like to promote `selectRelationCount` from preview to generally available.

- [x] https://github.com/prisma/prisma/issues/7807
- [x] https://github.com/prisma/prisma/issues/7893
- [x] https://github.com/prisma/prisma/issues/7299
- [x] https://github.com/prisma/prisma/issues/8050
- [x] #8631
- [x] https://github.com/prisma/prisma/issues/6312

### ~Stabilize filterJson (Nice to Have)~

- [ ] prisma/prisma#8224
- [ ] prisma/prisma#8874
- [ ] prisma/prisma#8977
- [ ] ~https://github.com/prisma/prisma/issues/8632~
- [ ] ~https://github.com/prisma/prisma/issues/7135~
  - **Update Sept 3rd:** We fixed some bugs, but won't stabilize `filterJson` for Prisma 3.

### Aggregation API

- [x] #9029

### Docs

- prisma/docs#2116
- update docs to reflect new attribute signatures
- remove preview flags from docs once everything above goes GA
- update examples to use new syntax / names / capabilities

# References

- [Why Prisma is Adopting Semver](https://www.prisma.io/blog/prisma-adopts-semver-strictly)
- [Internal Prisma 3.0 Planning Document](https://www.notion.so/prismaio/Prisma-3-0-Planning-678420bb49704202b9aead9dbe6b77b0)
- [Internal Node-API Project Board](https://github.com/orgs/prisma/projects/50)
- [Internal SQL Server Project Board](https://github.com/orgs/prisma/projects/48)
