### ISSUE TITLE
EPIC: re-design of `db seed` feature

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#8732]
`prisma db seed` is currently a Preview feature.

During this phase, we noticed [different issues](https://github.com/prisma/prisma/issues?q=is%3Aissue+label%3A%22topic%3A+db+seed%22) caused by the complexity of the current implementation.

The Migrations Team decided to remove the complexity and make it a lot easier to understand for users and to maintain.

The new implementation is in https://github.com/prisma/prisma/pull/8146

How it will work is that a `prisma.seed` property in the `package.json` of your project will be required if you want to use `prisma db seed`.

The CLI will give examples that can be copy-pasted.

If you are currently using the previous implementation of `prisma db seed` and upgrade to this new version then it will throw an error with an upgrade help message which should be easy to fix (add `prisma.seed` to the `package.json`)

`package.json` example for a JavaScript project
```js
  "prisma": {
    "seed": "node prisma/seed.js"
  } 
```

`package.json` example for a TypeScript project
```js
  "prisma": {
    "seed": "ts-node prisma/seed.ts"
  }
```

Example of a `prisma/seed.js`
```js
async function main() {
  await new Promise((resolve) => setTimeout(resolve, 100))
  console.log('Hello from seed.js')
}

main()
  .then(() => console.log('Goodbye from seed.js'))
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
```

What needs to done for releasing the "new" `db seed`:
- [x] Review and merge https://github.com/prisma/prisma/pull/8146
- [x] QA db seed
- [x] Update docs https://github.com/prisma/docs/pull/2161
- [x] https://github.com/prisma/prisma/issues/8033 
- [x] e2e https://github.com/prisma/e2e-tests/issues/1806
- [ ] Update https://github.com/prisma/prisma/issues/5161
- [ ] Close issues and let users know that they can use the new version https://github.com/prisma/prisma/issues?q=is%3Aissue+label%3A%22topic%3A+db+seed%22+is%3Aopen

**Comment by Jolg42** [comment]
It's possible to try it out with a specific version of the Prisma CLI like this:

```
npm install -D prisma@2.30.0-integration-db-seed-new-behavior.1

# Then run 
prisma db seed --preview-feature

# db seed is also integrated in
prisma migrate reset
prisma migrate dev
```

Or by using npx with the specific version:
```
npx prisma@2.30.0-integration-db-seed-new-behavior.1 db seed --preview-feature
```

**Comment by jasonkuhrt** [comment]
Note this will work and is cleaner IMO:

```js
"prisma": {
    "seed": "ts-node prisma/seed"
  }
```

**Comment by tobiasdiez** [comment]
May I suggest that the error handling part (copied from the above example)
```
main()
  .then(() => console.log('Goodbye from seed.js'))
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
```
may be moved to Prisma's cli code, i.e one only exports the `main` method and prisma takes care of the invocation. The main reason is that sometimes you do not want to exit in case there is an error during seeding. For example, if one uses `generate --watch` or `jest --watch` using `seed` to initialize tests. In the former case you prefer to be notified about the error, and in the latter the test should fail -- however, you don't really want to exit the calling process.

**Comment by Jolg42** [comment]
Hi @tobiasdiez indeed, exiting and not the best in some cases. This is just an example and in this implementation here you are free to change it as you need.
We removed the "magic" around export and invocation to simplify but that also means you can write a small layer that does that in your project.

**Comment by Jolg42** [comment]
Closing, rest is tracked in https://github.com/prisma/prisma/issues/8628

I'll create an issue to have better suggestion for ESM module projects help output.
