### ISSUE TITLE
PCO: Prisma Client Tracing Epic

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#9601]
## Problem
Right now we don't know where the Prisma Client is spending its time. We have a couple techniques for measuring time, but they provide segments of time that don't give you the full picture. 

By not having the complete timeline:

- We're not able to spot performance regressions and don't have a feedback loop to improve performance over time.
- It's hard and time-consuming to troubleshoot problems that users bring to us.
- We're not able to fend off benchmarks done by competitors.

## Goals

- **Not just for Prisma Engineers:** Easy and quick for our users to run and get a better sense of where the Prisma Client is spending its time.

- **Cross-Cutting:** Tracing should be end-to-end. You should be able to start a trace in your application and use the same tracing in the TS/Go client and the Query Engine.
    - In one of our user interviews, someone had tracing setup for their entire request-response lifecycle, but the Prisma Client was a black box for them.
    - By default we would initialize traces in the Prisma Client, but we should also allow users to pass application-wide trace IDs into the Prisma Client, so the Prisma Client becomes one span across your application.
    - Should be able to pass traces through to the database as well
    - Be able to see how queries break down into multiple subqueries and how long those subqueries take

- **Foundation to Improve Incrementally:** Make it easy to add sub-traces over time as we learn what data we need to troubleshoot better.
    - Start with just the basics
    - Sampling (configurable, later)
    - Filtering traces (configurable, later), users may not care about Prisma Client internals.

- **Uses a Standard:** Easy to plug into Cloud providers like DataDog, AWS X-Ray and GCP Tracing, HoneyComb, and LightStep.

### Milestone 1

If you've instrumented your application, the generated trace id from your app will be passed through Prisma Client all the way into an SQL comment.

- [x] #9602
- [x] #10002
- [x] ~#10010~
- [x] #10003
- [x] ~#10005~
- [x] #10006
- [x] #10004
- [x] #10310

### Milestone 2
We've setup the foundation to be able to collect and send traces from both Typescript and Rust. 

The Typescript side of the Prisma Client is able to hook into the existing tracing foundation setup by the user's application. The Typescript client is able to pass the necessary tracing configuration to the engine so it too can send spans to a trace collector.

- [x] https://github.com/prisma/prisma-engines/issues/2829 required before moving forward
- [x] #11093
- [ ] https://github.com/prisma/prisma-engines/issues/2859
- [x] #11474

### Milestone 3

We now have the foundation to send traces and adding new spans is easy. We learn what level of detail is important to our users and what the most important spans we should be tracking are.

- [x] https://github.com/prisma/prisma-engines/issues/2860
- [x] #10007
- [x] #10008
- [x] #10009
- [ ] #9605

### Milestone 4 (later)

The Prisma Client and Query Engine send their own trace events. They don't need to rely on the outer application being instrumented.

_TBD_

## References

- Community Issue: https://github.com/prisma/prisma/issues/1806
- Internal Solution Document: https://www.notion.so/prismaio/Tracing-b4ff34e0ea8a448cadb513570d7df5f4

**Comment by chrbala** [comment]
Is this no longer being worked on? It looks like this hasn't been active since January.

**Comment by matthewmueller** [comment]
Hey @chrbala, it's been a bit stalled as the team is focused on wrapping up MongoDB. But rest assured, we're making incremental progress week-by-week here and will have something more to share soon.

**Comment by garrensmith** [comment]
I'm closing this for a newer epic.

**Comment by moacirosa** [comment]
Could link the new one? Wanna follow this progress.

**Comment by garrensmith** [comment]
Ah sorry. The new one is in an internal repo. I'm going to re-open this one and update here.

**Comment by garrensmith** [comment]
I'm closing this for the new epic which is now publically available at https://github.com/prisma/client-planning/issues/21
